#!/bin/bash
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

counter=1
for file in /etc/nginx/sites-available/*; do
    echo -e "\n############################### [$counter] ###############################"
    echo -e "##\033[33;1m         $file \033[m"
    echo -e "###################################################################"
    grep -E "(server_name|root|index|listen|proxy_pass|return|rewrite|location|try_|ssl_certificate\\s)" $file | grep -v "^\s*#"
    counter=$((counter+1))
done
echo ""

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
