#!/bin/bash
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
filename=$1
tempfile=$(mktemp)
cat "$filename" > "$tempfile"

sed -Ei 's/(#.*$)//g' "$tempfile" # 주석 제거
sed -Ei '/^\s*$/d' "$tempfile" # 빈 줄 제거

echo ""
cat "$tempfile"
echo ""
rm "$tempfile"
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
