#!/bin/bash
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

# 사용자 입력
PORT_FROM=$1
PORT_TO=$2

CONF_DIR="/etc/nginx/sites-available/nx-redirect-${PORT_FROM}_${PORT_TO}.conf"

sudo touch $CONF_DIR
sudo chmod 777 $CONF_DIR

echo "server {" > ${CONF_DIR}
echo "    listen ${PORT_FROM} ;" >> ${CONF_DIR}
echo "    listen [::]:${PORT_FROM} ;" >> ${CONF_DIR}
echo "" >> ${CONF_DIR}
echo "    location / {" >> ${CONF_DIR}
echo "         proxy_pass http://127.0.0.1:${PORT_TO};" >> ${CONF_DIR}
echo "         proxy_set_header X-Real-IP \$remote_addr;" >> ${CONF_DIR}
echo "         proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;" >> ${CONF_DIR}
echo "         proxy_set_header Host \$http_host;" >> ${CONF_DIR}
echo "    }" >> ${CONF_DIR}
echo "}" >> ${CONF_DIR}
echo "" >> ${CONF_DIR}

sudo chmod 755 $CONF_DIR
sudo ln -s ${CONF_DIR} /etc/nginx/sites-enabled/

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
